# Page settings
baseurl = "https://omer-akbas.github.io/yazgan-sove/"
title = "Yazgan Sove"
languageCode = "tr-tr"
theme = "hugo-elate-theme"
publishDir = "docs"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "yazgan söve"
  description = "yazgan söve"
  email = "yazgansove@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = "AIzaSyDsRen2A8i09lZSVhCYG6_lYNEzg-ZfKRs"

  # Navigation
  [params.navigation]
    brand = "Yazgan Söve"
    home = "Anasayfa"
    work = "Söveler"
    testimonials = "Referanslarımız"
    services = "Servis"
    about = "Hakkımızda"
    contact = "İletişim"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Dış ve İç Cephe Süslemeleri"
    subtitle = 'Yapılarınıza görkemli bir görüntü kazandırmanızın en kolay yolu.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Keşif"
    description = "Binanızda söve uygulanacak yerler tespit edilir. Kullanılacak söveler belirlenir. İmal edilerek, montajı yapılır."
    url = "contact"
    button = "Şimdi Ara"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Montaj"
    description = "Binanızın estetiğini ve izolasyonunu artıracak olan söveler imal edilir ve binanıza montajı yapılır."
    url = "#"
    button = "İletişim"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Sonuç"
    description = "Söve uygulamasından sonra; binanızın dış cephesi estetik bir görünüm kazanır ve izolasyonu artar."
    url = "#"
    button = "Harita"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Video izle"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=FoviiRtm0ws"


  # Söveler
  [params.work]
    enable = true
    title = "Söve İmalatı"
    description = "İstenilen ölçü ve ebatlarda söve imalatımız vardır."
    # footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "sove11.jpeg"
      alt = "Sove 11"
      title = "YS 11"
      subtitle = "Yazgan Sove 11"

    [[params.work.row]]
      img = "sove12.jpeg"
      alt = "Sove 12"
      title = "YS 12"
      subtitle = "Yazgan Sove 12"

    [[params.work.row]]
      img = "sove13.jpeg"
      alt = "Sove 13"
      title = "YS 13"
      subtitle = "Yazgan Sove 13"

    [[params.work.row]]
      img = "sove14.jpeg"
      alt = "Sove 14"
      title = "YS 14"
      subtitle = "Yazgan Sove 14"

    [[params.work.row]]
      img = "sove15.jpeg"
      alt = "Sove 15"
      title = "YS 15"
      subtitle = "Yazgan Sove 15"

    [[params.work.row]]
      img = "sove16.jpeg"
      alt = "Sove 16"
      title = "YS 16"
      subtitle = "Yazgan Sove 16"

  # Referanslrımız
  [params.testimonials]
    enable = true
    title = "Referanslarımız"
    description = "Referanslarımızdan bazıları."

    [[params.testimonials.item]]
      # quote = "&ldquo;⭐⭐⭐⭐⭐&rdquo;"
      # quote = "⭐⭐⭐⭐⭐"
      foto = "asli.jpeg"
      person = 'Bergamalı Aslı Garden'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      # quote = "&ldquo;⭐⭐⭐⭐⭐&rdquo;"
      # quote = "⭐⭐⭐⭐⭐"
      foto = "betoncu.jpeg"
      person = 'Çandarlı Betoncu İnşaat'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      # quote = "⭐⭐⭐⭐⭐"
      foto = "yavaser.jpeg"
      person = 'Yavaşer İnşaat'
      img = "person3.jpg"
      alt = "Person3"
    



  # Söve
  [params.services]
    enable = true
    title = "Söve"
    description = "Pencere ve kapı kenarlarına uygulanan dekoratif profillere verilen addır. Bunun yanında halk arasında tüm dekoratif bina süsleme elemanlarına (kat silmesi, saçak silmesi, çatı silmesi, denizlik profili, köşe profili, kolon, sütun, harpuşta, payanda, kilit taşı v.b.) verilen genel ad olarak da bilinmektedir."

    [[params.services.item]]
      title = "Teknik Veriler"
      description = "Isı iletkenlik hesap değeri / 0,035 W/mk, Zehir içermeyen / klorofloro karbon içermez, Hidrokloroflorokarbon / TSEN 13163 (HCFC) içermez, Buhar difüzyon direnç katsayısı / 20-80, Su emmeArası / %0-5, Mekanik direnç / 50-150 kpa (5-15 ton/m≤) Maks, Yangın Sınıfın / DIN 4102 B-1 alevlenmez, Kullanım sıcaklığı / -175 / +185"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Üretim Ham Maddesi"
      description = "İnşaat sektöründe yapının özellik ve tasarımına göre en yaygın olarak rağbet gören ahşap söve, taş söve, mermer söve, beton söve (prekast), PVC söve, alçı söve olanları olmuştur. Özellikle dünyada ve Türkiye’de ısı yalıtım sistemlerinin (mantolama sistemleri) gelişmesi bu sistemlerin ihtiyaçlarına daha iyi cevap verecek, bu sistemlerle mükemmel uyum gösterecek söve elemanların ihtiyacını doğurmuştur."
      icon = "icon-layers2"
    
    # [[params.services.item]]
    #   title = "Photo &amp; Video"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #   icon = "icon-video2"

    # [[params.services.item]]
    #   title = "CMS &amp; eCommerce"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
    #   icon = "icon-monitor"

  # Hakkımızda
  [params.about]
    enable = true
    title = "Hakkımızda"
    description = "2000 yılından beri kuzey ege bölgesinde inşaat ve ısı yalıtım sektörüne hizmet vermekteyiz. Bizler için her zaman müşteri memnuniyeti ön planda olmuştur ve böyle olmayada devam edecektir."

    # [[params.about.item]]
    #   name = "Özkan ÖZMEN"
    #   position = "Söveci"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person1.jpg"
    #   alt = "Person1"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-linkedin", "#"]
    #   ]

    # [[params.about.item]]
    #   name = "Özkan ÖZMEN"
    #   position = "Söveci"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person2.jpg"
    #   alt = "Person2"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-github", "#"]
    #   ]

    # [[params.about.item]]
    #   name = "Özkan ÖZMEN"
    #   position = "Usta"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person3.jpg"
    #   alt = "Person3"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-dribbble", "#"]
    #   ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Yazgan Söve"
    # background = "full_image_1.jpg"
    background = "guzel.jpeg"

    description = "Yapılarınıza görkemli bir görüntü kazandırmanızın en kolay yolu."
   
    # [[params.counters.item]]
    #   description = "Finished projects"
    #   icon = "icon-briefcase"
    #   from = 0
    #   to = 89
    #   interval = 50
    #   speed = 5000

    # [[params.counters.item]]
    #   description = "Lines of code"
    #   icon = "icon-code"
    #   from = 0
    #   to = 2343409
    #   interval = 50
    #   speed = 5000

    # [[params.counters.item]]
    #   description = "Cups of coffee"
    #   icon = "icon-cup"
    #   from = 0
    #   to = 1302
    #   interval = 50
    #   speed = 5000

    # [[params.counters.item]]
    #   description = "Happy clients"
    #   icon = "icon-people"
    #   from = 0
    #   to = 52
    #   interval = 50
    #   speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "İletişim"
    description = "Detaylı bilgi almak için lütfen bizimle iletişime geçiniz."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Çandarlı Mah. Sucu Hafız Cad. No: 27A, Dikili<br> İzmir"],
        ["icon-phone", "0 (532) 511 95 15 - 0 (533) 022 62 00"],
        ["icon-envelope", "yazgansove@gmail.com"],
        ["icon-globe", '<a href="http://yazgansove.com/" target="_blank">yazgansove.com</a>']
      ]

    name = "Ad"
    email = "Email"
    phone = "Telefon"
    message = "Mesaj"
    button = "Gönder"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Yazgan Söve. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]